name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.17.1
homepage: https://github.com/ryanheise/audio_service

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  flutter_isolate:
    git:
      url: https://github.com/Stardust2water/flutter_isolate.git
      ref: master
  flutter_cache_manager: ^3.3.1
  js: ^0.6.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audioservice
        pluginClass: AudioServicePlugin
      ios:
        pluginClass: AudioServicePlugin
      macos:
        pluginClass: AudioServicePlugin
      web:
        pluginClass: AudioServicePlugin
        fileName: audio_service_web.dart
